files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths: 1
  final-newline: 1
  function-name-format: 1
  id-name-format: 1
  indentation: 1
  leading-zero: 1
  mixin-name-format: 1
  nesting-depth: 1
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-ids: 1
  no-important: 0
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  placeholder-name-format: 1
  property-sort-order:
    - 1
    - order: 'smacss'
  quotes: 1
  shorthand-values: 1
  single-line-per-selector: 0
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format: 1
